# YOLOv8 Vehicle Detection Configuration

# Model settings
model_path: 03_MODELS/yolov8s.pt
class_list_path: 04_DATA/parking_area/class_list.txt

# Target vehicle classes (TANPA MOTOR/MOTORCYCLE)
target_vehicle_classes:
  2: car     # COCO ID untuk car
  5: bus     # COCO ID untuk bus  
  7: truck   # COCO ID untuk truck

# Keywords untuk fallback filtering
parking_vehicle_keywords:
  - car
  - bus
  - truck

# Video paths
video_paths:
  - 04_DATA/parking_area/video/park1.mp4
  - 04_DATA/parking_area/video/park2.mp4
  - 04_DATA/parking_area/video/park3.mp4
  - 04_DATA/parking_area/video/park4.mp4

# Video validation settings
min_width: 640
min_height: 360

# Detection parameters
conf_threshold: 0.3
iou_threshold: 0.5
min_area: 500
max_area: 50000

# Processing settings
frame_skip: 3           # Process every 3rd frame
resize_width: 1920      # Full HD width for full screen
resize_height: 1080     # Full HD height for full screen
fullscreen_mode: true   # Enable full screen display

# Tracking settings for parking detection
tracking_enabled: true
max_distance_threshold: 100    # Maximum distance to consider same vehicle
min_parking_time: 2.0         # Minimum time (seconds) to consider parked
min_moving_time: 0.8          # Minimum time (seconds) to consider moving
max_movement_threshold: 10    # Increased threshold to filter camera shake
cleanup_timeout: 5.0          # Remove vehicles not seen for this long

# Output settings
output_dir: 08_LOGS_OUTPUT/output
save_results: true
show_display: true

# Ground truth data for testing
ground_truth_data:
  park1.mp4: 5
  park2.mp4: 8  
  park3.mp4: 4
  park4.mp4: 7

# Default test points for each video (Full screen detection)
default_test_points:
  park1.mp4:
    - [0, 0]
    - [1920, 0] 
    - [1920, 1080]
    - [0, 1080]
  park2.mp4:
    - [0, 0]
    - [1920, 0]
    - [1920, 1080] 
    - [0, 1080]
  park3.mp4:
    - [0, 0]
    - [1920, 0]
    - [1920, 1080]
    - [0, 1080]
  park4.mp4:
    - [0, 0]
    - [1920, 0]
    - [1920, 1080]
    - [0, 1080]
